PROVINCIAS = [{"label":"A Coruña","value":"a-coruna"},
    {"label":"Álava-Áraba","value":"alava-araba"},
    {"label":"Albacete","value":"albacete"},
    {"label":"Alicante\/Alacant","value":"alicante-alacant"},
    {"label":"Almería","value":"almeria"},
    {"label":"Asturias","value":"asturias"},
    {"label":"Ávila","value":"avila"},
    {"label":"Badajoz","value":"badajoz"},
    {"label":"Barcelona","value":"barcelona"},
    {"label":"Burgos","value":"burgos"},
    {"label":"Cáceres","value":"caceres"},
    {"label":"Cádiz","value":"cadiz"},
    {"label":"Cantabria","value":"cantabria"},
    {"label":"Castellón\/Castelló","value":"castellon-castello"},
    {"label":"Ceuta","value":"ceuta"},
    {"label":"Ciudad Real","value":"ciudad-real"},
    {"label":"Córdoba","value":"cordoba"},
    {"label":"Cuenca","value":"cuenca"},
    {"label":"Girona","value":"girona"},
    {"label":"Granada","value":"granada"},
    {"label":"Guadalajara","value":"guadalajara"},
    {"label":"Gipúzcoa\/Gipuzkoa","value":"gipuzcoa-gipuzkoa"},
    {"label":"Huelva","value":"huelva"},
    {"label":"Huesca","value":"huesca"},
    {"label":"Illes Balears","value":"illes-balears"},
    {"label":"Jaén","value":"jaen"},
    {"label":"La Rioja","value":"la-rioja"},
    {"label":"Las Palmas","value":"las-palmas"},
    {"label":"León","value":"leon"},
    {"label":"Lleida","value":"lleida"},
    {"label":"Lugo","value":"lugo"},
    {"label":"Madrid","value":"madrid"},
    {"label":"Málaga","value":"malaga"},
    {"label":"Melilla","value":"melilla"},
    {"label":"Murcia","value":"murcia"},
    {"label":"Navarra","value":"navarra"},
    {"label":"Ourense","value":"ourense"},
    {"label":"Palencia","value":"palencia"},
    {"label":"Pontevedra","value":"pontevedra"},
    {"label":"Salamanca","value":"salamanca"},
    {"label":"Santa Cruz de Tenerife","value":"santa-cruz-de-tenerife"},
    {"label":"Segovia","value":"segovia"},
    {"label":"Sevilla","value":"sevilla"},
    {"label":"Soria","value":"soria"},
    {"label":"Tarragona","value":"tarragona"},
    {"label":"Teruel","value":"teruel"},
    {"label":"Toledo","value":"toledo"},
    {"label":"Valencia\/València","value":"valencia-valencia"},
    {"label":"Valladolid","value":"valladolid"},
    {"label":"Vizcaya\/Bizkaia","value":"vizcaya-bizkaia"},
    {"label":"Zamora","value":"zamora"},
    {"label":"Zaragoza","value":"zaragoza"}]


PUESTOS = ['desarrollador-de-software-desarrolladora-de-software']
